
# Samplesheets

unmapped_bams_list: "/home/fb343/git/gatk4-germline-snps-indels/resources/lowpass_hmb/bam_list.tsv"

input_fofn: "/home/fb343/git/gatk4-germline-snps-indels/resources/lowpass_hmb/mapping_file.tsv"

# Main output dir

outdir: "/gpfs/ycga/scratch60/christakis/fb343/gatk/germline_gatk"

# Reference files

scattered_calling_interval: "/home/fb343/git/gatk4-germline-snps-indels/resources/lowpass_hmb/hg38_wgs_scattered_calling_intervals.txt"

fasta: "/gpfs/ycga/project/christakis/fb343/databases/variant_calling_pipeline_hg38/genome.fasta"

dbSNP_vcf: "/gpfs/ycga/project/christakis/fb343/databases/Homo_sapiens_assembly38.dbsnp138.vcf"
 
known_indels_mills: "/gpfs/ycga/project/christakis/fb343/databases/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
 
known_indels_dbSNP: "/gpfs/ycga/project/christakis/fb343/databases/Homo_sapiens_assembly38.known_indels.vcf.gz"

sequence_grouping: "/home/fb343/git/gatk4-germline-snps-indels/resources/original_public_sources/sequence_grouping.txt"

sequence_grouping_unmapped: "/home/fb343/git/gatk4-germline-snps-indels/resources/original_public_sources/sequence_grouping_with_unmapped.txt"


